FROM jenkins/jenkins:lts

USER root
RUN apt-get update -qq && \
    apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list && \
    apt-get update -qq && \
    apt-get install -qqy docker-ce-cli && \
    groupadd docker && \
    usermod -aG docker jenkins

USER jenkins
RUN jenkins-plugin-cli --plugins "docker-workflow"
