pipeline {
  agent any
  stages {
    stage('Tofu Plan') {
      steps {
        sh 'cd infra/iac && tofu init && tofu validate && tofu plan'
      }
    }
    stage('Tofu Apply') {
      steps {
        sh 'cd infra/iac && tofu apply -auto-approve'
      }
    }
  }
}
