controller:
  serviceAccount: jenkins-sa
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - blueocean
    - configuration-as-code
    - credentials-binding
    - nodejs
    - github
  admin:
    username: admin
    password: admin
  serviceType: NodePort
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  additionalExistingSecrets:
    - name: jenkins-ghcr-secret
      keyName: username
    - name: jenkins-ghcr-secret
      keyName: token
  JCasC:
    enabled: true
    configScripts:
      jenkins-casc-configs: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                - usernamePassword:
                    scope: GLOBAL
                    id: "ghcr-creds"
                    username: "${jenkins-ghcr-secret-username}"
                    password: "${jenkins-ghcr-secret-token}"
                    description: "GitHub Container Registry credentials"
agent:
  podName: jenkins-agent
  namespace: infra
  serviceAccount: jenkins-sa
  enabled: true
  runAsUser: 0
  image:
    registry: ghcr.io
    repository: alex-carvalho/sandbox/jenkins-agent
    tag: latest
    pullPolicy: Always
  customJenkinsLabels: "infra jenkins"
  privileged: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
persistence:
  enabled: true
  size: 8Gi